### PR TITLE
feture: .webm / resume video

### PR DESCRIPTION
**Pull request by lucasmedi**
Hi Tony! Hope you're well.

@yurigoytacaz asked me for help to add a couple features, as listed below:
- Added .webm extension to OpenFileDialog filter;
- Added option to resume video playback.

To resume video playback I added three new properties on MySettings class, one to enable it and another to save the corresponding position (TimeSpan) value obtained on MainWindow close events. The third happened because this approach led me to serialization problems for TimeSpan, solved by transforming it to string on Save and back again to TimeSpan on Load.

If you have any issues, let me know!

### CODE REVIEW

**Comment by yurigoytacaz** [comment]
nice! (= 
it works life a charm

**Comment by rider45** [comment]
Hi Tony, 1st thank you for the nice video player. I am not a programmer so i can not help there. But i do have a suggestion.
ADD and option to config. on how to close the screen saver IE: ESC, mouse move or mouse click.

kevin

**Comment by TesterEU** [comment]
Great app! Now I can play video on all display (app has options fit and canter only but it works!).
If you can add loop option (not infinity play video) then your App will be awsome for everyone.
Thank you :)

**Comment by tonyfederer** [comment]
This pull request conflicts with the changes I made in version 1.1.  However, I added the resume playback option in version 1.2

**Pull request closed without merging**
